version: '3.8'
services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: patient_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: spring-app
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "5050:5050"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/patient_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin

volumes:
  postgres_data:
