services:
  billing-db:
    image: postgres:15
    container_name: billing-db
    restart: always
    environment:
      POSTGRES_DB: billing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports: []
    volumes:
      - billing_postgres_data:/var/lib/postgresql/data

  billing-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billing-service
    restart: always
    depends_on:
      - billing-db
    ports:
      - "5052:5052"
      - "9091:9091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://billing-db:5432/billing_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin

volumes:
  billing_postgres_data:
